### ISSUE TITLE
Support for ON DELETE CASCADE

### ISSUE THREAD

**Issue by bf** [holistics/dbml#7]
It would be nice to have support for `ON DELETE CASCADE` in dbdiagram.io

**Comment by nntai** [comment]
Hi @bf, thank you for your idea. Could you share more about what you need with `ON DELETE CASCADE`?
By this time, if you need this feature for documentation, you could use our note feature to show it in the tooltip when hovering on the table.
```
Table orders {
  id int [pk]
  user_id int [not null, unique]
  status orders_status
  created_at varchar [note: "When order created"]
}

Table order_items {
  order_id int [note: "Will be delete when order deleted"]
  product_id int    
  quantity int [default: 1]
}
```
![Screen Shot 2019-07-12 at 17 09 30](https://user-images.githubusercontent.com/15927583/61120743-d9246900-a4c7-11e9-88fb-27f6a16b5cfc.png)

**Comment by ben-eb** [comment]
@nntai I think there is currently no way to express the below in DBML:

> ```sql
> CREATE TABLE products (
>     product_no integer PRIMARY KEY,
>     name text,
>     price numeric
> );
> 
> CREATE TABLE orders (
>     order_id integer PRIMARY KEY,
>     shipping_address text
> );
> 
> CREATE TABLE order_items (
>     product_no integer REFERENCES products ON DELETE RESTRICT,
>     order_id integer REFERENCES orders ON DELETE CASCADE,
>     quantity integer,
>     PRIMARY KEY (product_no, order_id)
> );
> ```
> Restricting and cascading deletes are the two most common options. `RESTRICT` prevents deletion of a referenced row. `NO ACTION` means that if any referencing rows still exist when the constraint is checked, an error is raised; this is the default behavior if you do not specify anything. (The essential difference between these two choices is that `NO ACTION` allows the check to be deferred until later in the transaction, whereas `RESTRICT` does not.) `CASCADE` specifies that when a referenced row is deleted, row(s) referencing it should be automatically deleted as well.

source: https://www.postgresql.org/docs/11/ddl-constraints.html

**Comment by ufhy** [comment]
up

**Comment by nntai** [comment]
Hi @bf, @ufhy, @ben-eb, we are updating the parser to support syntax: `ON DELETE/ON UPDATE...` but we can not find the best way to express it in DBML syntax. Do you guys have any ideas?
Btw, we did open-source our parser and also the CLI in [packages folder](https://github.com/holistics/dbml/tree/master/packages), you could check it.

**Comment by ben-eb** [comment]
@nntai You could use the settings and make it a feature restricted to the long-form definition:

```

**Comment by zkwsk** [comment]
I'm also looking for support for `ON DELETE` and `ON UPDATE`. Any progress since this was last posted?

**Comment by connorshea** [comment]
I tried importing my `schema.rb`, but it choked on the `on_delete: :cascade` part: https://github.com/connorshea/VideoGameList/blob/0a8bc67101de5e7aa27648487bee65c7dc70a296/db/schema.rb

It works fine if I remove all those foreign keys with `on_delete`, but it'd be nice if it were supported properly :)

It looks like DBML supports `ON DELETE` since #29 was merged, but neither the docs nor dbdiagram.io have been updated yet.

**Comment by phuongduyphan** [comment]
Hi @zkwsk , @connorshea 

Glad to announce that we've just released the latest dbml version that supports referential actions. You can check the docs here: https://www.dbml.org/docs/#relationship-settings.

Ps: The syntax is also supported in dbdiagram as well.

**Comment by phuongduyphan** [comment]
#54

**Comment by NewEXE** [comment]
@phanbaominh tnank you! Maybe it make sense to update sample DB on dbdiagram.io with demonstating of this feature?

**Comment by phanbaominh** [comment]
Hi @NewEXE 
Thanks for the suggestion, we'll be sure to implement that in future updates of dbdiagram.io

**Comment by PierrickI3** [comment]
Hi, was this implemented at all? I still get an error when trying to add `[delete: ]` in a diagram

**Comment by naivary** [comment]
Hi, is this still not supported?

**Comment by TeaNguyen** [comment]
@PierrickI3 Did you define the referential actions within an inline form relationship? As stated in [our docs](https://www.dbml.org/docs/#relationship-settings), relationship settings are not supported for the inline form relationship.

@naivary Not really. This feature is supported.

**Comment by PierrickI3** [comment]
@TeaNguyen I missed that. Thank you!
